services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=electricity'
      - 'POSTGRES_PASSWORD=academy'
      - 'POSTGRES_USER=academy'
    ports:
      - '127.0.0.1:5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U academy -d electricity" ]
      interval: 5s
      timeout: 5s
      retries: 3

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/electricity
      SPRING_DATASOURCE_USERNAME: academy
      SPRING_DATASOURCE_PASSWORD: academy
    ports:
      - "8080:8080"
