services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=electricity'
      - 'POSTGRES_PASSWORD=academy'
      - 'POSTGRES_USER=academy'
    ports:
      - '127.0.0.1:5432:5432'
